-- Q1. Total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) AS revenue_from_customers
FROM customer GROUP BY gender;

-- Q2. Customers using a discount who spent more than the average
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating)::numeric, 2) AS average_product_rating
FROM customer GROUP BY item_purchased ORDER BY average_product_rating DESC LIMIT 5;

-- Q4. Average purchase amount: Standard vs Express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount)::numeric, 2) AS average_purchase_amount
FROM customer WHERE shipping_type IN ('Standard', 'Express') GROUP BY shipping_type;

-- Q5. Spend comparison: Subscribers vs Non-subscribers
SELECT subscription_status, COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount)::numeric, 2) AS average_spend, SUM(purchase_amount) AS total_revenue
FROM customer GROUP BY subscription_status ORDER BY total_revenue DESC;

-- Q6. Top 5 products with the highest percentage of discount usage
SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*)) * 100, 2) AS discount_rate
FROM customer GROUP BY item_purchased ORDER BY discount_rate DESC LIMIT 5;

-- Q7. Customer segmentation based on previous purchases
WITH customer_type AS (
    SELECT customer_id,
        CASE WHEN previous_purchases <= 1 THEN 'New'
             WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
             ELSE 'Loyal' END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type GROUP BY customer_segment;

-- Q8. Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts WHERE item_rank <= 3;

-- Q9. Subscription likelihood among repeat buyers
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer WHERE previous_purchases > 5 GROUP BY subscription_status;

-- Q10. Revenue by Age Group
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer GROUP BY age_group ORDER BY total_revenue DESC;
